// Single place to point the app at a backend. '' = same-origin local server.py.
// Once the AWS API Gateway is live, set this to e.g. 'https://kw67yao8v7.execute-api.us-east-1.amazonaws.com'
// and update api() below to attach an Authorization header once sign-in is wired up.
const API_BASE='';
const $=s=>document.querySelector(s);let user,rooms=[],bookings=[],busy=[],pending,cancelId;let toastTimer;
async function api(path,data){const r=await fetch(API_BASE+'/api/'+path,{method:data?'POST':'GET',headers:data?{'Content-Type':'application/json'}:{},body:data?JSON.stringify(data):undefined});const value=await r.json();if(!r.ok)throw Error(value.message||'Request failed');return value}
function toast(msg,error=false){$('#toast').textContent=msg;$('#toast').className=error?'error':'';$('#toast').style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').style.display='none',5500)}
const fmt=s=>new Date(s).toLocaleString('en-SG',{timeZone:'Asia/Singapore',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'});
function view(v){if(v==='insights'&&!['staff','admin'].includes(user?.role))return;if(v==='admin'&&user?.role!=='admin')return;['find','bookings','insights','admin'].forEach(x=>$('#'+x).hidden=x!==v);document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.view===v));if(v==='admin')loadAdminRooms().catch(e=>toast(e.message,true))}
async function refresh(){[rooms,bookings,busy]=await Promise.all([api('rooms'),api('bookings'),api('availability?date='+$('#date').value)]);renderRooms();renderBookings()}
function renderRooms(){const filtered=rooms.filter(r=>r.capacity>=Number($('#capacity').value));$('#roomCount').textContent=filtered.length+' rooms';$('#rooms').innerHTML=filtered.map(r=>`<article class="room"><div class="room-top"><span class="room-id">${r.id}</span><span class="capacity">${r.capacity} people</span></div><div class="room-body"><h3>${r.name}</h3><div class="location">${r.location}</div><div class="amenities">${r.amenities.split(',').map(a=>`<span>${a}</span>`).join('')}</div><div class="slot-label">SELECT A START TIME · 1 HOUR</div><div class="slots">${Array.from({length:9},(_,i)=>{const h=i+9,start=`${$('#date').value}T${String(h).padStart(2,'0')}:00:00+08:00`,taken=busy.some(b=>b.room===r.id&&b.start===start),past=new Date(start)<=new Date();return `<button class="slot" data-room="${r.id}" data-start="${start}" ${taken||past?'disabled':''} title="${taken?'Already reserved':past?'Past time':'Book this slot'}">${h}:00</button>`}).join('')}</div></div></article>`).join('');document.querySelectorAll('.slot:not(:disabled)').forEach(b=>b.onclick=()=>{pending={room:b.dataset.room,start:b.dataset.start};$('#summary').textContent=`${rooms.find(r=>r.id===pending.room).name} · ${fmt(pending.start)} · 1 hour`;$('#confirm').showModal()})}
function cards(list,staff=false){return list.length?list.map(b=>{const dt=new Date(b.start),future=dt>new Date(),canCheck=b.status==='confirmed'&&b.attendance==='pending'&&new Date()>=dt&&new Date()<=new Date(dt.getTime()+900000);return `<article class="booking"><div class="detail"><h3>${rooms.find(r=>r.id===b.room)?.name||b.room}</h3><p>${fmt(b.start)} · 1 hour</p><p>Reference ${b.id}${staff?' · '+b.user:''}</p></div><span class="badge">${b.status==='cancelled'?'cancelled':b.attendance==='attended'?'checked in':b.attendance==='no_show'?'no-show':'confirmed'}</span>${b.status==='confirmed'&&future?`<button data-cancel="${b.id}">Cancel</button>`:''}${canCheck?`<button data-check="${b.id}">Check in</button>`:''}</article>`}).join(''):'<div class="empty"><h2>Your next session starts here.</h2><p>No bookings yet. Choose a room and make some time for focused work.</p></div>'}
function renderBookings(){const mine=bookings.filter(b=>b.user===user.id);$('#count').textContent=mine.filter(b=>b.status==='confirmed'&&new Date(b.start)>new Date()).length;$('#bookingList').innerHTML=cards(mine);if(['staff','admin'].includes(user.role)){$('#staffList').innerHTML=cards(bookings,true);const active=bookings.filter(b=>b.status==='confirmed');$('#metrics').innerHTML=[['Confirmed bookings',active.length],['Checked in',active.filter(b=>b.attendance==='attended').length],['Recorded no-shows',active.filter(b=>b.attendance==='no_show').length]].map(([l,v])=>`<div class="metric">${l}<strong>${v}</strong></div>`).join('')}document.querySelectorAll('[data-cancel]').forEach(b=>b.onclick=()=>{cancelId=b.dataset.cancel;$('#cancelDialog').showModal()});document.querySelectorAll('[data-check]').forEach(b=>b.onclick=async()=>{try{const r=await api('check-in',{id:b.dataset.check});toast(r.message);await refresh()}catch(e){toast(e.message,true)}})}
function adminView(v){['rooms','analytics','forecast'].forEach(x=>$('#admin-'+x).hidden=x!==v);document.querySelectorAll('.subtab').forEach(b=>b.classList.toggle('active',b.dataset.admin===v));if(v==='analytics')loadAnalytics().catch(e=>toast(e.message,true));if(v==='forecast')loadForecast().catch(e=>toast(e.message,true))}
document.querySelectorAll('.subtab').forEach(b=>b.onclick=()=>adminView(b.dataset.admin));
function barChart(title,rows,labelKey,valueKey,unit=''){const max=Math.max(...rows.map(r=>r[valueKey]),1);return `<div class="chart-card"><h3>${title}</h3>${rows.map(r=>`<div class="bar-row"><span>${r[labelKey]}</span><div class="bar-track"><div class="bar-fill" style="width:${(r[valueKey]/max*100).toFixed(1)}%"></div></div><span>${r[valueKey]}${unit}</span></div>`).join('')}</div>`}
async function loadAnalytics(){$('#analyticsBody').textContent='Loading…';const d=await api('admin/analytics/reservations');$('#analyticsSource').textContent=d.source+(d.date_from?` · ${d.date_from} to ${d.date_to}`:'');if(!d.total){$('#analyticsBody').innerHTML='<div class="empty"><h2>No historical data loaded.</h2></div>';return}
$('#analyticsBody').innerHTML=`<div class="forecast-note"><strong>${d.total.toLocaleString()}</strong> historical reservations · avg length <strong>${d.avg_duration_minutes} min</strong> · <strong>${Math.round(d.weekend_share*100)}%</strong> on weekends</div><div class="analytics-grid">${barChart('Reservations by room (top 12)',d.by_room,'room_id','count')}${barChart('Reservations by weekday',d.by_weekday,'weekday','count')}${barChart('Reservations by hour of day',d.by_hour.map(r=>({...r,hour:r.hour+':00'})),'hour','count')}${barChart('Reservations by month',d.by_month.map(r=>({...r,month:'Month '+r.month})),'month','count')}</div>`}
async function loadForecast(){$('#forecastBody').textContent='Loading…';const d=await api('admin/analytics/forecast');if(!d.total_samples){$('#forecastBody').innerHTML='<div class="empty"><h2>No historical data loaded.</h2></div>';return}
$('#forecastBody').innerHTML=`<div class="forecast-note"><strong>Method:</strong> ${d.method}. Based on ${d.total_samples.toLocaleString()} logged reservations over ~${d.weeks_of_history} weeks.</div><div class="analytics-grid">${barChart('Busiest weekday + hour combinations',d.busiest_slots.map(r=>({...r,label:r.weekday+' '+r.hour+':00'})),'label','expected_per_week',' /wk')}${barChart('Rooms likely to stay busiest',d.likely_busiest_rooms,'room_id','expected_per_week',' /wk')}</div>`}
let adminRooms=[];
async function loadAdminRooms(){adminRooms=await api('admin/rooms');renderAdminRooms()}
function renderAdminRooms(){$('#roomList').innerHTML=adminRooms.length?adminRooms.map(r=>`<article class="room-row${r.active?'':' inactive'}"><div class="room-row-info"><span class="room-id">${r.id}</span><strong>${r.name}</strong><span>${r.capacity} people · ${r.location}</span><span class="amenities-inline">${r.amenities||'No amenities listed'}</span></div><span class="badge">${r.active?'active':'inactive'}</span><button type="button" data-edit="${r.id}">Edit</button></article>`).join(''):'<div class="empty"><h2>No rooms yet.</h2><p>Add your first room above.</p></div>';document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editRoom(b.dataset.edit))}
function editRoom(id){const r=adminRooms.find(x=>x.id===id);if(!r)return;$('#roomId').value=r.id;$('#roomName').value=r.name;$('#roomCapacity').value=r.capacity;$('#roomLocation').value=r.location;$('#roomAmenities').value=r.amenities;$('#roomActive').checked=!!r.active;$('#roomSubmit').textContent='Save changes';$('#roomCancel').hidden=false;$('#roomName').focus()}
function resetRoomForm(){$('#roomForm').reset();$('#roomId').value='';$('#roomActive').checked=true;$('#roomSubmit').textContent='Add room';$('#roomCancel').hidden=true}
$('#roomCancel').onclick=resetRoomForm;
$('#roomForm').onsubmit=async e=>{e.preventDefault();const id=$('#roomId').value;const data={name:$('#roomName').value,capacity:$('#roomCapacity').value,location:$('#roomLocation').value,amenities:$('#roomAmenities').value,active:$('#roomActive').checked};try{const r=await api(id?'admin/rooms/update':'admin/rooms/create',id?{...data,id}:data);toast(r.message);resetRoomForm();await loadAdminRooms()}catch(err){toast(err.message,true)}};
async function init(){const s=await api('session');user=s.user;if(!$('#date').value)$('#date').value=s.today;$('#date').min=s.today;if(!user){$('#login').showModal();return}$('#identity').replaceChildren();const name=document.createElement('span');name.textContent=user.name;const btn=document.createElement('button');btn.textContent='Switch account';btn.onclick=async()=>{await api('logout',{});location.reload()};$('#identity').append(name,btn);$('#staffTab').hidden=!['staff','admin'].includes(user.role);$('#adminTab').hidden=user.role!=='admin';await refresh()}
$('#login').addEventListener('cancel',e=>e.preventDefault());$('#loginForm').onsubmit=async e=>{e.preventDefault();try{await api('demo-login',{user:$('#account').value});$('#login').close();await init()}catch(e){toast(e.message,true)}};
$('#confirmForm').onsubmit=async e=>{e.preventDefault();$('#bookButton').disabled=true;try{const r=await api('bookings',pending);$('#confirm').close();toast(r.message);await refresh();view('bookings')}catch(e){toast(e.message,true);await refresh()}finally{$('#bookButton').disabled=false}};
$('#back').onclick=()=>$('#confirm').close();$('#keep').onclick=()=>$('#cancelDialog').close();$('#doCancel').onclick=async()=>{try{const r=await api('cancel',{id:cancelId});$('#cancelDialog').close();toast(r.message);await refresh()}catch(e){toast(e.message,true)}};
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>view(b.dataset.view));$('#date').onchange=()=>{if($('#date').value)refresh().catch(e=>toast(e.message,true))};$('#capacity').onchange=renderRooms;init().catch(e=>toast(e.message,true));
